[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
skip-string-normalization = true

[tool.mypy]
python_version = '3.8'
strict = true
implicit_optional = false
show_error_codes = true
show_column_numbers = true

[[tool.mypy.overrides]]
module = ['numpy.*', 'pandas.*', 'pandaset.*', 'rich.*', 'scipy.*']
ignore_missing_imports = true

[tool.ruff]
line-length = 88
target-version = 'py38'
extend-select = [
  # flake8-bugbear
  'B',
  # flake8-blind-except
  'BLE',
  # flake8-comprehensions
  'C4',
  # flake8-commas
  'COM',
  # pydocsytle
  'D',
  # eradicate
  'ERA',
  # isort
  'I',
  # flake8-import-conventions
  'ICN',
  # flake8-no-pep420
  'INP',
  # flake8-implicit-str-concat
  'ISC',
  # pep8-naming
  'N',
  # NumPy-specific rules
  'NPY',
  # pandas-vet
  'PD',
  # pygrep-hooks
  'PGH',
  # flake8-pie
  'PIE',
  # flake8-use-pathlib
  'PTH',
  # flake8-quotes
  'Q',
  # flake8-return
  'RET',
  # flake8-raise
  'RSE',
  # Ruff-specific rules
  'RUF',
  # flake8-bandit
  'S',
  # flake8-self
  'SLF',
  # flake8-simplify
  'SIM',
  # flake8-print
  'T20',
  # flake8-type-checking
  'TCH',
  # flake8-tidy-imports
  'TID',
  # flake8-2020
  'YTT',
]
ignore = [
  'D100',  # pydocstyle: Missing docstring in public module
  'D203',  # pydocstyle: 1 blank line required before class docstring
  'D213',  # pydocstyle: Multi-line docstring summary should start at the second line
  'PD901', # pandas-vet: df is a bad variable name. Be kinder to your future self.
]

[tool.ruff.flake8-quotes]
docstring-quotes = 'double'
inline-quotes = 'single'
multiline-quotes = 'double'

[tool.ruff.per-file-ignores]
'__init__.py' = ['D104']
'__main__.py' = ['D103', 'D104']
'geometry.py' = ['N803', 'N806']
